- biggraphite/cli/bg_carbon_cache.py
Unlike in upstram code, we cannot use sys.arg[0]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/18)
> Call twisted with carbon-cache

- biggraphite/test_utils.py
- tests/test_accessor.py
- tests/test_carbon.py
- tests/test_import_whisper.py
- tox.ini
- tox only installs minimal dependancies for each env
- removed --install-option, allowing reuse of wheels
- If CASSANDRA_HOME is not set, corresponding (slow) tests are skipped
allowing to run lightweight tests quickly.
- If a test fail, cancel the whole run (so Travis replies faster)
- test_carbon uses FakeAccessor, so accessor tests are now the only
tests to run with a real Cassandra
Also makes some small improvements, like making FakeAccessor and
Accessor more similar and raising test coverage a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/21)
> Faster tests.

- biggraphite/accessor.py
- biggraphite/graphite_utils.py
- biggraphite/metadata_cache.py
- biggraphite/plugins/carbon.py
- biggraphite/plugins/graphite.py
- biggraphite/test_utils.py
- requirements.txt
- tests/test_carbon.py
- tests/test_graphite.py
- tests/test_metadata_cache.py
The DiskCache is implemented with lmdb, an on-disk file DB that can be accessed by multiple processes. Keys are metric names, values are json-serialised metadata.
In deployment the graphite storage dir is used as a rendez-vous point where all processes (carbon, graphite, ...) can find the metadata.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/20)
> Add a cache for metric metadata.

- biggraphite/accessor.py
- biggraphite/metadata_cache.py
- tests/test_metadata_cache.py
- We were limited to 10M of local cache
- LMDB won't accept unicode objects, so encode metric names to
UTF-8 (probably safer anyway)
- we cache decoded jsons metadata but they included metric names, taking
quite some memory (while the idea behind caching is that there are few
retentions policies in use at any given time)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/25)
> Fix memory leak and bug

- biggraphite/accessor.py
- biggraphite/cli/import_whisper.py
- biggraphite/metadata_cache.py
- biggraphite/plugins/carbon.py
- biggraphite/plugins/graphite.py
- biggraphite/test_utils.py
- tests/test_accessor.py
- tests/test_graphite.py
- tests/test_graphite_utils.py
- tests/test_import_whisper.py
- tests/test_metadata_cache.py
So that downsampling can happen at write and aggregation server-side,
the Accessor needs to have metadata when it reads/writes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/34)
> Accessor uses Metric instead of names

- biggraphite/accessor.py
- biggraphite/cli/import_whisper.py
- biggraphite/drivers/cassandra.py
- biggraphite/plugins/carbon.py
- biggraphite/plugins/graphite.py
- biggraphite/test_utils.py
- requirements.txt
- tests/test_accessor.py
- tests/test_cassandra.py
- tests/test_graphite.py
- tests/test_import_whisper.py
Aggregator used to be a string named carbon_aggregation, and retention a list of (point, precision).
This API-only change makes it easier to do server-side aggregation.
It also removes the support for xfilesfactor which we don't use and won't support with server-side aggregation at first (we still store it though)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/38)
> Make aggregator an enum and retention an object

- requirements.txt
With earlier versions we would get the following error:
File "/home/travis/build/criteo/biggraphite/.tox/pypy-coverage/site-packages/progressbar/bar.py", line 108, in update
if self.redirect_stderr and sys.stderr.tell():
IOError: [Errno 29] Illegal seek: '<stderr>'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/42)
> Force install of progressbar2>=3.9.3

- biggraphite/cli/clusters_diff.py
This makes travis cry because numpy takes ages to compile and
isn't strictly needed to have something functional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/41)
> clusters_diff: remove the hard dependency on numpy

- biggraphite/drivers/cassandra.py
If parent directories do not exist, this costs one more round trip. But
as most metrics have siblings, this saves time overall.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/51)
> Do not create parent directory if it exists

- biggraphite/drivers/cassandra.py
- biggraphite/metadata_cache.py
- biggraphite/plugins/carbon.py
- biggraphite/plugins/graphite.py
- tests/test_carbon.py
- tests/test_metadata_cache.py
No need to create them before we use them. This will also prevent
creating the cache as root before we start using it as 'graphite'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/84)
> plugins: create cache and accessor lazilly

- biggraphite/accessor.py
- biggraphite/cli/bgutil.py
- biggraphite/cli/command_repair.py
- biggraphite/cli/command_test.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/memory.py
- biggraphite/metadata_cache.py
- biggraphite/utils.py
- tests/test_cassandra.py
- tests/test_metadata_cache.py
Currently very slow, probably even too slow to be usable
on an actual setup. We need a way to parallelize that.
Also make some changes in create() and exists(): exists() will
check if the parent directory exists too, this allows fsck
to ignore metrics and run only on directories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/99)
> Add bgutil repair and repair() functions

- biggraphite/drivers/cassandra.py
I did not see any comments or documentation suggesting there is a rationale
behind the use of ANY, and thus believe this is a potential bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/102)
> Use ONE instead of ANY for write consistency

- biggraphite/accessor.py
- biggraphite/drivers/cassandra.py
- biggraphite/test_utils.py
- tests/test_cassandra.py
- TWCS is a new compaction strategy that replaces DTCS in >3.8
- Change _EXPECTED_POINTS_PER_READ to 2000 to make sure that reading
a day of date reads only one sstable.
- Change _MIN_ROW_SIZE_MS to 6 hours to make sure that we have too
many queries to do when reading points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/100)
> cassandra: add support for TimeWindowCompactionStrategy and tweak DTCS

- biggraphite/drivers/cassandra.py
- biggraphite/utils.py
- tests/test_utils.py
We write mostly individual datapoints so we really don't need compression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/103)
> cassandra: add a way to disable compression

- biggraphite/accessor.py
- biggraphite/cli/command_repair.py
- biggraphite/drivers/cassandra.py
- biggraphite/metadata_cache.py
- tests/test_command_repair.py
- tests/test_metadata_cache.py
See #60.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/119)
> bgutil: add ways to shard repairs

- biggraphite/metadata_cache.py
- biggraphite/plugins/graphite.py
- requirements.txt
This should fix #135. I have no idea why this code was here
in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/136)
> graphite: don't remove metadata_cache when refreshing metric

- biggraphite/drivers/cassandra.py
This way, as soon as it has fetched all its elements it
will stop reading SSTables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/142)
> cassandra: add a LIMIT to help Cassandra stop reading

- biggraphite/drivers/cassandra.py
- biggraphite/drivers/memory.py
- biggraphite/test_utils.py
- tests/test_carbon.py
- tests/test_cassandra.py
Double dots ('..') has the same meaning as '//' in a filesystem
so we should not create empty directories in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/139)
> accessor: do not create empty directories for double-dots

- biggraphite/accessor.py
- biggraphite/cli/command_read.py
- biggraphite/plugins/graphite.py
- tests/test_accessor.py
This PR should also save one fallback object creation request for the graphite plugin.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/153)
> Automatic stage selection from metric timestamp for bgutil read

- biggraphite/accessor.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/memory.py
- biggraphite/graphite_utils.py
- biggraphite/metadata_cache.py
- biggraphite/plugins/carbon.py
- biggraphite/plugins/graphite.py
- biggraphite/test_utils.py
- biggraphite/utils.py
- requirements.txt
- setup.py
- tests/test_carbon.py
- tests/test_graphite.py
- tests/test_graphite_utils.py
- tests/test_metadata_cache.py
- don't perform useless operations if the source stage is
the same as the output stage.
- really use a tuple factory instead of creating new objects
for each point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/161)
> cassandra: read path optimizations

- biggraphite/accessor.py
- biggraphite/cli/bgutil.py
- biggraphite/drivers/_delayed_writer.py
- biggraphite/drivers/_downsampling.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/memory.py
- biggraphite/plugins/carbon.py
- tests/test_carbon.py
- tests/test_cassandra.py
- tests/test_drivers_downsampling.py
- tests/test_glob_utils.py
- tests/test_graphite.py
The delayed writer will separate low res and high res points
and write the low resolution points slower. This gives
batching for free because these points usually have the same
timestamp and a value that changes over time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/162)
> biggraphite: add a delayed writer

- biggraphite/metadata_cache.py
- tests/test_metadata_cache.py
Before it would return True when a miss was being cached.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/167)
> metadata_cache: fix DiskCache.has_metric()

- biggraphite/drivers/cassandra.py
- biggraphite/glob_utils.py
- tests/test_glob_utils.py
Initial work for #169 
Summary:
* Adds a (simplistic) graphite pattern parser to our glob utils that can be reused
* Makes use of said parser in the Cassandra driver implementation to take advantage of prefix queries (because we are currently using prefix SASI indexes) on metric name components whenever possible
Warning:
* This has been tested quickly, but not thoroughly benchmarked yet
Future work:
* Add brace selector parsing, and use it to generate several queries using the generated values whenever possible (e.g. a{b,c,d}.b would generate 3 queries, for ab.b / ac.b / ad.b, instead of “a%.b” + potentially costly post-filtering)
* Caveat: beware of situations with character selectors inside the brace selector! (-> naive implementation will not be correct!)
---
This change is [<img …
> Initial implementation of query optimization for Cassandra

- .travis.yml
- pom.xml
- Specify the version of Python
- Specify the version of the JDK, and install it
- Add execution of existing Java tests. Run once to save time (on the
slave that checks pyjama).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/188)
> Update TRAVIS in order to test Java tools

- biggraphite/metadata_cache.py
- if a process crashed or was stopped abruptly, stale readers remain. So
we clean stale readers just after we open the database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/202)
> metadata_cache: fix LMDB stale reader issue

- tox.ini
Makes fast iteration on tests less of a hassle (issue #179).
Sample use cases (same as non-discovery unittest):
tox -- tests                                          # by module
tox -- tests.test_glob_utils                          # by file
tox -- tests.test_accessor.TestMetric                 # by test class
tox -- tests.test_graphite.TestFinder.test_find_nodes # by test method
Unfortunately, due to the strange way unittest handles arguments (see its
usage text for details) it is not easy pass the usual arguments (catch,
failfast, verbose) in both the default and the posargs calls.
You can pass them through the posargs if you need them:
tox -- -cfv tests.test_glob_utils.TestGlobUtils
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Enable posargs in tox

- biggraphite/drivers/_delayed_writer.py
- biggraphite/plugins/carbon.py
Make this effective for resolution starting at 40min. In
the future the delay should probably be a function of the precision
with a fixed max.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/230)
> delayed_writer: change it for common values

- biggraphite/metadata_cache.py
- tests/test_metadata_cache.py
database ttl is not updated for metric that are always a cache hit.
Force a cache miss when ttl expired in cache to force a re-update on database.
Want to check if it will trigger a thunderclap on database
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/226)
> Fix update of ttl for database

- biggraphite/drivers/cassandra.py
This fix race conditions when using multiple cluster with
the asyncore reactor.
See https://datastax-oss.atlassian.net/browse/PYTHON-697
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/235)
> cassandra: only use one kind of _CappedConnection

- biggraphite/metadata_cache.py
Add some randomness to the TTL to avoid killing
the database when you've done a very quick rolling restart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/237)
> metadata_cache: spread expirations

- biggraphite/accessor.py
when running repair I got this stack trace
```Feb 14 11:09:17 graphite-global-cache-bg01-am5 bgutil[55441]: Traceback (most recent call last):
Feb 14 11:09:17 graphite-global-cache-bg01-am5 bgutil[55441]: File "/opt/graphite/pypy/bin/bgutil", line 11, in <module>
Feb 14 11:09:17 graphite-global-cache-bg01-am5 bgutil[55441]: load_entry_point('biggraphite==0.7.0', 'console_scripts', 'bgutil')()
Feb 14 11:09:17 graphite-global-cache-bg01-am5 bgutil[55441]: File "/opt/graphite/pypy/site-packages/biggraphite/cli/bgutil.py", line 78, in main
Feb 14 11:09:17 graphite-global-cache-bg01-am5 bgutil[55441]: opts.func(accessor, opts)
Feb 14 11:09:17 graphite-global-cache-bg01-am5 bgutil[55441]: File "/opt/graphite/pypy/site-packages/biggraphite/cli/command_repair.py", line 82, in run
Feb 14 11:09:17 …
```
> If metadata is not set, return defaults values

- .travis.yml
- requirements.txt
IPython6 need python>3.3, so we force ipython<5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/268)
> Fix biggraphite install

- biggraphite/accessor.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/memory.py
- biggraphite/metadata_cache.py
- biggraphite/plugins/carbon.py
- tests/test_cassandra.py
It's easier to hikack get_metric() here than to store updated_on
in metadata, so we add another argument to get_metric()
> cassandra/carbon: make sure we change updated_on only for writes

- biggraphite/drivers/cassandra.py
Usefull when searching metrics created during a time range.
Before this change, we only had read_on and updated_on to filter metrics.
Signed-off-by: Thibault Chataigner <t.chataigner@criteo.com>
> Add created_at in metrics_metadata

- USAGE.md
- biggraphite/accessor.py
- biggraphite/cli/command_syncdb.py
- biggraphite/cli/command_write.py
- biggraphite/drivers/cassandra.py
- tests/test_cassandra.py
- tests/test_command_syncdb.py
- tests/test_command_write.py
This will make everything easier because Cassandra isn't really
happy when multiple carbon processes try to create new tables at the same time.
> bgutil syncdb: add a way to create datapoint tables

- biggraphite/drivers/cassandra.py
Signed-off-by: Thibault Chataigner <t.chataigner@criteo.com>
> Skip corrupt metrics in _CassandraAccessor.map

- biggraphite/drivers/cassandra.py
- biggraphite/plugins/graphite.py
- tests/test_graphite.py
Before this patch, different queries would have the same cache
key because only the pattern would be used to differenciate queries.
Now we use all attributes.
This would mostly have an impact when leaves_only is set to True.
> graphite: fix the find_nodes cache key

- biggraphite/drivers/cassandra.py
Signed-off-by: Jean-Francois Weber-Marx <jf.webermarx@criteo.com>
In biggraphite/drivers/cassandra.py in syndb it should be self._execute_data(query) instead of self._execute_metadata(query)
> cassandra.py: fix _execute_data in syncdb

- biggraphite/cli/command_list.py
- tests/test_command_list.py
This fix affect the behavior of 'read', 'du', 'copy' and 'list' commands.
Currently accessor.glob_metric_names() is used but return in some cases invalid results
graphite_glob() post filter accessor.glob_metric_names() to ensure output correctness
A better but more involved fix would be to fix glob_metric_names() cassandra implementation and trust its output but some code might rely on the current behavior.
> Use glob_utils.graphite_glob() to list metrics & directories.

- .travis.yml
- CONTRIBUTING.md
- biggraphite/drivers/cassandra.py
Also make sure we deal with metrics with empty id, config (those would
be created by calls to fetch_points() for non-existing metrics).
Also bump Cassandra to 3.11.2 for tests.
> cassandra: do not call get_metric() each time we call fetch_points()

- biggraphite/cli/bgutil.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/elasticsearch.py
- tools/elasticsearch/import-metrics.py
- Add support for labels in the import-elasticsearch scripts (for tests)
- Implement create_metric() in elasticsearch.py (very basic implementation)
- Add code the create missing indices when necessary (+ basic mapping)
> elasticsearch: basic support to create metrics

- biggraphite/drivers/elasticsearch.py
- tools/elasticsearch/import-metrics.py
Today, the length is not accurate as a.b would have a length of 1
However, renaming length to depth would be clearer (a.b would have a depth of 1)
> Rename length to depth to bring clarity

- biggraphite/drivers/elasticsearch.py
Globstar can be a component as well as a subcomponent (broken by #353)
> ES: fix _parse_regexp_component

- biggraphite/drivers/elasticsearch.py
`p0`... `px` are already keywords in the index mapping (see #354 / 02690897ece6ec9f4f9d3f6b4888267948d94795). 
They should be removed from the query.
> ES: remove "keyword" in p*s queries

- biggraphite/drivers/elasticsearch.py
p0... px are already keywords in the index mapping (see #354 /
0269089). They should be removed from
the query.
Same as #360 but on a forgotten case...
> ES: remove keyword in p*s queries

- biggraphite/drivers/elasticsearch.py
- tests/test_elasticsearch.py
Example:
foo.bar.{baz,qux*}
was not returning the correct result: a 'terms' query did not
match the regexp.
This case is now handled.
> ES: fix regexp in value sequence

- biggraphite/drivers/elasticsearch.py
Default size is 10: only the 10 "biggest" directories were returned.
Increase that limit to 10.000.
> ES: fix aggregation query size on directory glob matching

- biggraphite/drivers/cassandra.py
- biggraphite/drivers/elasticsearch.py
- biggraphite/drivers/hybrid.py
- biggraphite/utils.py
- tests/drivers/test_hybrid.py
Allow to have separate accessors for metadata and data.
* When `driver` flag is provided, build a regular accessor
* When `data_driver` and `metadata_driver` flags are provided, build a composite accessor
> Provide hybrid accessor

- biggraphite/drivers/elasticsearch.py
- biggraphite/drivers/ttls.py
- tests/drivers/test_elasticsearch.py
If the index of the fetched document is not the same as the one of today,
recreate the metric in the current index.
> Recreate metric in current index if index is old.

- biggraphite/drivers/elasticsearch.py
- biggraphite/drivers/ttls.py
- tests/drivers/test_elasticsearch.py
The new unit test would have caused:
```
======================================================================
ERROR: test_fetch_points_updates_read_on (__main__.TestAccessorWithElasticsearch)
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests/drivers/test_elasticsearch.py", line 361, in test_fetch_points_updates_read_on
points = self.accessor.fetch_points(metric, 0, 1, metric.retention[0])
File "/home/cchary/dev/graphite/biggraphite/biggraphite/drivers/elasticsearch.py", line 651, in fetch_points
self.__update_read_on_on_need(metric)
File "/home/cchary/dev/graphite/biggraphite/biggraphite/drivers/elasticsearch.py", line 735, in __update_read_on_on_need
read_on_timestamp = ttls.str_to_timestamp(metric.read_on)
File …
```
> elasticsearch: fix fetch_points()

- tox.ini
Travis defines 3 envs:
* python 2.7
* python 3.6
* pypy
Tox did not have python 3.6 but python 3.
> Match tox configuration with Travis

- biggraphite/accessor.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/elasticsearch.py
- biggraphite/drivers/hybrid.py
- biggraphite/drivers/memory.py
- biggraphite/metadata_cache.py
- biggraphite/plugins/carbon.py
- tests/drivers/test_cassandra.py
- tests/drivers/test_elasticsearch.py
- tests/drivers/test_hybrid.py
A boolean modifying the behavior of a method can be confusing.
Callers with the need to touch the metric will have to call it manually
> Refactoring: remove touch attribute from get_metric

- biggraphite/drivers/elasticsearch.py
- tests/drivers/base_test_metadata.py
Without the fix, the test raises the following error:
```
======================================================================
ERROR: test_touch_without_create (__main__.TestAccessorWithElasticsearch)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/cchary/dev/graphite/biggraphite/tests/drivers/base_test_metadata.py", line 373, in test_touch_without_create
self.accessor.touch_metric(metric)
File "/home/cchary/dev/graphite/biggraphite/biggraphite/drivers/elasticsearch.py", line 661, in touch_metric
if not document.updated_on:
AttributeError: 'NoneType' object has no attribute 'updated_on'
```
> elasticsearch: ignore missing documents in touch_metric()

- biggraphite/drivers/cassandra.py
- biggraphite/drivers/elasticsearch.py
Currently it changes the database but not the object used
as a parameter. Since both are not synced, the next call
will re-trigger a database update even if there was no need
for it.
In elasticsearch also fetch the document only when we really
need, else we end up doing one synchronous query each time
we write a point.
> drivers: make sure touch_metric() also changes the metric

- biggraphite/drivers/elasticsearch.py
409 code means there is a conflict at document update time.
We do not need strong consistency on metadata so we can ignore an error
once in a while.
> ES: ignore 409 HTTP status codes on document update

- CONTRIBUTING.md
- README.md
- USAGE.md
* Remove Gemnasium (service is closed)
* Add Elasticsearch as supported metadata backend
* Document scripts to use tmpfs for tests
* Typo
> Improve documentation

- biggraphite/accessor.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/elasticsearch.py
- biggraphite/drivers/hybrid.py
- biggraphite/drivers/memory.py
- tests/test_utils.py
It brings confusion and is only called by tests.
> Removed clear method.

- requirements.txt
Add it as a required dependency.
> bgutil won't start without IPython

- biggraphite/drivers/elasticsearch.py
The previous code would update the latest index only, even
if the metric is on another one. Now we fetch the latest document
and we update read_on on this one.
> elasticsearch: fix read_on, again

- biggraphite/drivers/elasticsearch.py
- requirements.txt
- setup.py
Installing enum in python 3.6 will break everything.
> setup.py: include enum and futures only for python 2.7

- .gitignore
- biggraphite/drivers/cassandra.py
See CASSANDRA_DESIGN.md. We added a shard_id to avoid
data loss on restarts. On restart the data of some
given datapoints may be spread on several cassandra cells.
Limit of fetch data queries were computed with no
restart, and then may be too short in case of restarts.
This may create artificial loss at read time.
> Fix query limit while fetching points using cassandra

- biggraphite/plugins/carbon.py
Without this, metrics would all have updated_on set
to `now` meaning it would not get updated if the process
restarts before the ttl expiration (three days).
> carbon: make sure updated_on gets written

- biggraphite/accessor.py
- biggraphite/accessor_factory.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/hybrid.py
- tests/drivers/test_cassandra.py
- tests/test_accessor_factory.py
- tests/test_utils.py
- tests/test_utils_cassandra.py
When using the hybrid mode, data and metadata accessors are both updating read_on and update_on metadata.
This is a problem because this makes mandatory to specify the metadata storage configuration for the data accessor while it is not used.
The solution consist in passing a flag preventing the data accessor to use the metadata storage when the hybrid mode is used.
> Hybrid accessor: no longer make calls to data accessor for metadata actions

- biggraphite/drivers/cassandra.py
* For synchronous queries, use of a timer is mandatory (by API design).
* A query wrapper allows to count any query (synchronous or asynchronous).
> Monitor Cassandra queries

- CHANGELOG.md
- biggraphite/plugins/carbon.py
The metric creation process is asynchronous, metrics scheduled to be created are added to a queue and a thread process it to effectively create them in database.
This PR aims to monitor the enqueuing rate. The dequeuing rate where already monitored via `bg_creates` which I renamed `bg_creates_dequeued`.
> Improve observability on metric creation

- CHANGELOG.md
- biggraphite/plugins/carbon.py
I wrongly changed the "bg_creates" metric in PR #473. This PR restores "bg_creates" and increments the new metric "bg_creates_dequeued" at the right place.
> Improve observability on metric creation - fixing issue introduced in the previous commit

- CHANGELOG.md
- tools/graphiteindex/pom.xml
Fixes CVE-2017-12629
See: https://nvd.nist.gov/vuln/detail/CVE-2017-12629
> Upgrade Lucene to 7.1.0 version

- biggraphite/drivers/cassandra.py
- tests/drivers/base_test_metadata.py
This fix aims to prevent a "list index out of range" exception to be raised when the metric name doesn't exists in database:
```
Unhandled Error
Traceback (most recent call last):
File "/opt/graphite/pypy/site-packages/twisted/
result = inContext.theWork()
File "/opt/graphite/pypy/site-packages/twisted/
inContext.theWork = lambda: context.call(ctx, 
File "/opt/graphite/pypy/site-packages/twisted/
return self.currentContext().callWithContext(
File "/opt/graphite/pypy/site-packages/twisted/
return func(*args,**kw)
--- <exception caught here> ---
File "/opt/graphite/pypy/site-packages/biggraphite/
self._createOneMetric()
File "/opt/graphite/pypy/site-packages/biggraphite/
existing_metric = self.accessor.get_metric(
File "/opt/graphite/pypy/site-packages/biggraphite/
return next(iter(
File …
```
> Fix list index out of range in _get_metrics when the metric doesn't exists

- biggraphite/glob_utils.py
Current implementation for Cassandra didn't use the metadata cache because glob metrics was already getting metadata without cache. This commit re-enable it by calling only glob_metric_names.
> Make sure glob on cassandra use cache

- CHANGELOG.md
- biggraphite/plugins/carbon.py
- requirements.txt
- setup.py
The Prometheus client changed the metric API from version 0.4.0.
This change makes it compatible to the newer API and freeze prometheus_client to version 0.5.0.
> Adapt biggraphite to use the lastest version of prometheus client and bump to 0.13.12

- CHANGELOG.md
- biggraphite/plugins/carbon.py
- requirements.txt
- setup.py
The Prometheus client changed the metric API from version 0.4.0.
This change makes it compatible to the newer API and freeze prometheus_client to version 0.5.0.
> Adapt biggraphite to use the lastest version of prometheus client and bump to 0.14.5

- CHANGELOG.md
- biggraphite/cli/command_copy.py
- biggraphite/cli/command_write.py
- biggraphite/cli/import_whisper.py
- biggraphite/cli/web/namespaces/biggraphite.py
- biggraphite/metadata_cache.py
- biggraphite/metric.py
- biggraphite/plugins/carbon.py
- biggraphite/plugins/graphite.py
- tests/cli/test_command_delete.py
- tests/cli/test_command_du.py
- tests/cli/test_command_graphite_web.py
- tests/cli/test_command_list.py
- tests/cli/test_command_read.py
- tests/cli/test_command_stats.py
- tests/cli/test_command_web.py
- tests/drivers/base_test_metadata.py
- tests/drivers/test_drivers_delayed_writer.py
- tests/drivers/test_drivers_downsampling.py
- tests/drivers/test_elasticsearch.py
- tests/drivers/test_hybrid.py
- tests/drivers/test_memory.py
- tests/plugins/test_carbon.py
- tests/plugins/test_graphite.py
- tests/test_glob_utils.py
- tests/test_metadata_cache.py
- tests/test_metric.py
- tests/test_utils.py
Today for every Metric object, we create a MetricMetadata object. This is a waste of memory since the same metadata can be shared by several metrics.
This change aims to rationalize the number of MetricMetadata objects created in biggraphite. I replaced all the calls to MetricMetadata's constructor by a call to MetricMetadata.create() who will create a MetricMetadata if necessary or return an existing one.
What do you think?
TODO:
- I know there is a problem with the xfilesfactor that is used as a dictionary key. It could be a problem because of the float representation.
- Add documentation/comments
- cleanup asserts in MetricMetadata.create()
> Share MetricMetadata objects as much as possible

- biggraphite/accessor_cache.py
This is the only issue I've found so far running on Python 3.6 instead of Python 2.7 (an upgrade I'm trying to do now since Python 2.7 EOLs this year). Applying this patch results in correct rendering in graphite and correct ingestion through bg-carbon-cache.
> fix accessor cache on python 3.x

- docker/graphite-aggregator-cache/Dockerfile
- docker/graphite-web/Dockerfile
Added a layer (RUN pip install cassandra-driver) at the beginning af Dockerfile for graphite-aggregator-cache and graphite-web containers.
Since the installation and build of this driver is the one that takes most of the time during the build, that part  of the build will not be processed during subsequent builds triggered by local modification of biggraphite sources.
> Optimized Docker rebuild of graphite containers images

- tests-requirements.txt
- tools/install-deps.sh
- fixed cassandra tarball url in the installation of dependencies
- removed django-tagging as dependency in test-requirements as this is already a dependency of graphite-web
> Fixed travis tests

- biggraphite/drivers/cassandra.py
The _LazyPreparedStatements function was called without the last two arguments (supposed to set data read/write consistency).
This was preventing the setting of these arguments to values different form  the default ones.
> Fixed cassandra read/write consistency level in _LazyPreparedStatements

- biggraphite/cli/command_copy.py
- biggraphite/cli/command_write.py
- biggraphite/cli/import_whisper.py
- biggraphite/drivers/cassandra.py
- biggraphite/drivers/elasticsearch.py
- biggraphite/metric.py
- biggraphite/plugins/carbon.py
- tests/cli/test_bgutil.py
- tests/cli/test_command_copy.py
- tests/cli/test_command_delete.py
- tests/cli/test_command_du.py
- tests/cli/test_command_graphite_web.py
- tests/cli/test_command_list.py
- tests/cli/test_command_read.py
- tests/cli/test_command_stats.py
- tests/drivers/base_test_metadata.py
- tests/drivers/test_cassandra.py
- tests/drivers/test_drivers_delayed_writer.py
- tests/drivers/test_elasticsearch.py
- tests/drivers/test_memory.py
- tests/plugins/test_carbon.py
- tests/plugins/test_graphite.py
- tests/test_accessor.py
- tests/test_glob_utils.py
- tests/test_metadata_cache.py
- tests/test_metric.py
- tests/test_utils.py
When an aggregator-cache restarts, all the metrics received gets touched and flood Cassandra with updates. It's not an issue when one restarts but it causes problems when many of them restart at the same time.
This fix consist in waiting for the metric creation process to read the metric from Cassandra and to reflect the value of the field "updated_on" in the internal cache. During this time, the metric won't be touched.
This is what happens at restart:
> Wait metadata to be read before touching them

- CHANGELOG.md
- CONFIGURATION.md
- biggraphite/drivers/elasticsearch.py
- Make updated_on_ttl_sec, read_on_ttl_sec and read_on_sampling_rate configurable
- Update Elasticsearch driver documentation
> Add configuration keys for Elasticsearch driver

- biggraphite/drivers/cassandra.py
- tests/drivers/base_test_metadata.py
- tests/test_utils.py
graphite-web may still have a metric in its cache that have been deleted
in Cassandra. It will re-create the metric partially (every field to null
except name and read_on) when field 'read_on' is getting updated because
UPDATE and INSERT clauses in Cassandra behave like an UPSERT operation.
Adding 'IF EXISTS' makes sure that Cassandra won't create the metric if it
doesn't exists.
> Do not update read_on if the metric is not present

- CONFIGURATION.md
- biggraphite/drivers/cassandra.py
Setting BG_CASSANDRA_READ_ON_SAMPLING_RATE to 0 skips updating the read_on
> Make it possible to disable READ_ON updates

- biggraphite/plugins/carbon.py
- biggraphite/utils.py
- tests/plugins/test_carbon.py
- tests/test_utils.py
Add the ability to disable the creation of the metadata at run-time by creating a file in $GRAPHITE_ROOT/disable_metadata
> Disable metadata management at run-time

- biggraphite/settings.py
The strtobool() call fails saying that the module util does
not exist.
> Without this import there is a failure to use function.

- biggraphite/metric.py
- tests/test_accessor.py
- tests/test_metric.py
rational:
Aggregation "sum" is stored as "total" in cassandra.  "sum" is not recognized as a valid aggregation method the Aggregator class which is an enum (because sum is a builtin I assume) thus breaking the read to ES backend which uses graphite naming
> the aggregator name can now match regular carbon naming

- biggraphite/metric.py
- tests/test_metric.py
changed from 'is' to '==' for aggregation name comparison as it would
not match unicode in python2.7
> changed comparison for aggregator to match unicode

- .travis.yml
- biggraphite/cli/command.py
- biggraphite/cli/import_whisper.py
- biggraphite/cli/web/namespaces/bgutil.py
- biggraphite/cli/web/worker.py
- biggraphite/metadata_cache.py
- biggraphite/metric.py
Moving travis build to xenial instead of trusty, as this last one won't make our pypy tests working. This includes some linting fixes & minor test fixes.
> Upgrade travis build

- biggraphite/cli/bg_carbon_aggregator_cache.py
- biggraphite/cli/bg_carbon_cache.py
- setup.py
The recent cassandra_driver update triggered a reactor installation before starting to parse biggraphite configuration. This is triggering a failure because biggraphite can't initialize its own reactor, making the bg daemon fails.
Also, bumping to 0.14.20.
> Fix daemon launch by unregistering Twisted reactor

- biggraphite/cli/command_stats.py
- biggraphite/drivers/cassandra.py
This patch adds the possibility to create a new stats job to export estimated metrics & directories present in database, and extrapolate to now expired metrics or empty directories without scanning the whole database.
> Adding an experimental metadata database statistical analysis.

- .github/workflows/biggraphite.yml
- biggraphite/drivers/cassandra.py
When cleaning metrics, we're sequentialy listing all metrics in the
unfiltered way to do so. Therefore, adding a way to extract all those
for debug/catalog reasons.
This is not enabled by default, and is triggered only when method
is 'unfiltered' and the env. var CLEAN_DUMP_METRICS is set.
While I'm at it, disabling python 2 builds & checks.
> Dump all metrics names on disk when cleaning.
