criteo/biggraphite

.coveragerc, .travis.yml, tests-requirements.txt, tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/2)
=> Setup coveralls

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/4)
=> Fancy badges in README.md

biggraphite/accessor.py, biggraphite/test_utils.py, tests/test_accessor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/5)
=> Add support for directories

biggraphite/accessor.py, biggraphite/plugins/carbon.py, biggraphite/test_utils.py, tests-requirements.txt, tests/test_accessor.py, tests/test_carbon.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/6)
=> Plugin carbon

biggraphite/graphite_utils.py, tests/test_graphite_utils.py
Add several Graphite utility free functions:
* is_graphite_glob
* graphite_to_cassandra_glob
* filter_metrics
* get_graphite_metrics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/3)
=> Add Graphite utility class

biggraphite/accessor.py, biggraphite/plugins/graphite.py, tests/test_accessor.py
Also fixes small bugs and makes test faster.
There are no unit tests yet, but I wanted to get this out so as to help
sync'ing with the ongoing work on writing a real Finder.
I checked it worked by inserting points and viewing them in Graphite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/7)
=> Add a graphite finder

biggraphite/accessor.py, tests/test_accessor.py
This fixes a bug when the most detailed retention policy is more precise than a second.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/8)
=> Consider retention to check carbon_xfilesfactor

biggraphite/accessor.py, tests/test_accessor.py, tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/9)
=> Ignore test_utils to compute coverage

biggraphite/plugins/carbon.py, biggraphite/plugins/graphite.py, requirements.txt, setup.py, tests-requirements.txt, tests/test_graphite.py
Much of the work is upgrading setup.py to pull a yet-unreleased version of graphite-web
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/10)
=> Unit test the graphite plugin

biggraphite/accessor.py, biggraphite/test_utils.py, requirements.txt, tests/test_graphite.py, tests/test_graphite_utils.py
It can be used to write unit tests that run much faster than with a
local Cassandra.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/12)
=> Add a FakeAccessor and TestWithFakeAccessor

biggraphite/graphite_utils.py, biggraphite/plugins/carbon.py, biggraphite/plugins/graphite.py, tests/test_carbon.py, tests/test_graphite.py, tests/test_graphite_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/13)
=> Add proper Finder implementation

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/15)
=> Package plugins as well

biggraphite/cli/bg_carbon_cache.py, setup.py, tests-requirements.txt, tests/test_bg_carbon_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/16)
=> Add bg-carbon-cache to load the plugin

biggraphite/cli/bg_carbon_cache.py, tests/test_bg_carbon_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/17)
=> bg-carbon-cache manipulate sys.path like upstream

biggraphite/cli/import_whisper.py, biggraphite/test_utils.py, setup.py, tests/test_import_whisper.py
This packages the existing import_whisper, fixes bugs and adds tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/19)
=> Add bg-import-whisper and tests.

biggraphite/graphite_utils.py, biggraphite/plugins/carbon.py, tests/test_graphite_utils.py
- Add copyright notice
- Add a module-level Error base exception
- Rename ConfigException in ConfigError
No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/24)
=> Make graphite_utils more similar to other modules

biggraphite/cli/import_whisper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/26)
=> Fix bg-import-whisper option parsing

biggraphite/cli/import_whisper.py, tests/test_import_whisper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/27)
=> import_whisper: Handle input directories not ending with /

biggraphite/accessor.py, biggraphite/metadata_cache.py, biggraphite/plugins/graphite.py, tests/test_graphite.py, tests/test_metadata_cache.py
- Missing import
- Missing encode of unicode strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/29)
=> Fixes for graphite plugin (and tests)

biggraphite/cli/import_whisper.py, tests/test_import_whisper.py
It used to write twice every point present in multiple archives.
Also add tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/31)
=> bg-import-whisper: fix bug affecting few points

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/28)
=> README.md: add mailing list

README.md, biggraphite/accessor.py, biggraphite/plugins/graphite.py, biggraphite/test_utils.py, tests-requirements.txt, tests/test_accessor.py, tests/test_graphite.py, tests/test_import_whisper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/32)
=> graphite: support asynchronous reads

.travis.yml, biggraphite/accessor.py, biggraphite/cli/import_whisper.py, biggraphite/drivers/__init__.py, biggraphite/drivers/_utils.py, biggraphite/drivers/cassandra.py, biggraphite/graphite_utils.py, biggraphite/plugins/carbon.py, biggraphite/test_utils.py, tests/test_accessor.py, tests/test_carbon.py, tests/test_cassandra.py, tests/test_drivers_utils.py, tests/test_graphite.py, tests/test_graphite_utils.py, tests/test_import_whisper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/36)
=> Separate Cassandra from accessor

biggraphite/cli/clusters_diff.py, tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/37)
=> Add a script in biggraphite/cli/ to compute diff between two graphite clusters.

biggraphite/accessor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/43)
=> accessor: add some sugar to Retention and Stage

biggraphite/accessor.py, biggraphite/drivers/cassandra.py, biggraphite/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/45)
=> Support multiple resolutions in the database

biggraphite/drivers/downsampling.py, tests/test_drivers_downsampling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/44)
=> Implement circular buffer for downsampling

biggraphite/accessor.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/downsampling.py, biggraphite/plugins/graphite.py, tests/test_accessor.py
- Add a test downsampler that generates per-minute averages
- Make sure that we could read and aggregate averages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/46)
=> downsampling: add a stupid downsampler and fix average aggregation

biggraphite/drivers/downsampling.py, tests/test_drivers_downsampling.py
@iksaif: I did something wrong, I'm sorry. So I'm creating this new PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/48)
=> Implement aggregation mechanism

biggraphite/drivers/downsampling.py, tests/test_drivers_downsampling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/49)
=> Improve Downsampler to use actual metric metadata

CASSANDRA_DESIGN.md, CONTRIBUTING.md, README.md, biggraphite/DESIGN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/39)
=> Documents design

biggraphite/drivers/downsampling.py, biggraphite/metadata_cache.py, biggraphite/plugins/carbon.py, biggraphite/plugins/graphite.py, biggraphite/test_utils.py, setup.py, tests/test_accessor.py, tests/test_drivers_downsampling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/50)
=> Fix several bugs in BigGraphite

biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/52)
=> Set TTLs as a stopgap measure

biggraphite/drivers/cassandra.py, biggraphite/plugins/carbon.py, tests/test_carbon.py
This greatly reduce CPU usage as per https://goo.gl/xP5fD9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/54)
=> 	Make only one write every 100 wait for Cassandra

CONTRIBUTING.md, biggraphite/cli/clusters_diff.py, setup.py, tests/test_clusters_diff.py, tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/40)
=> Add test_clusters_diff.py

biggraphite/accessor.py, biggraphite/drivers/cassandra.py, biggraphite/plugins/graphite.py, biggraphite/test_utils.py, tests/test_accessor.py, tests/test_carbon.py, tests/test_cassandra.py, tests/test_import_whisper.py
This will allow to select a correct table for the specified stage as
well as to set TTLs.
As a result, it closes a few TODOs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/55)
=> Use stage instead of step in the API

biggraphite/drivers/_downsampling.py, biggraphite/drivers/cassandra.py, tests/test_drivers_downsampling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/59)
=> Return stage instead of step in Downsampler

CASSANDRA_DESIGN.md, biggraphite/accessor.py, biggraphite/drivers/cassandra.py, biggraphite/plugins/graphite.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/58)
=> Support for TTLs

biggraphite/drivers/cassandra.py, biggraphite/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/62)
=> Put metadata in a different keyspace

biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/64)
=> Limits the number of in flight requests to 300	

biggraphite/drivers/_utils.py, biggraphite/drivers/cassandra.py, tests/test_cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/65)
=> Fix deadlock on no downsampled point

biggraphite/drivers/cassandra.py
Handles comments left by @iksaif on review #58 after it was committed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/68)
=> Second round of tweaks for datapoints tables.

CASSANDRA_DESIGN.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/71)
=> cassandra: add keyspace documentation

biggraphite/accessor.py, tests/test_accessor.py, tests/test_carbon.py
Spelling "avg" should have been "average"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/72)
=> Fix carbon plugin "average" aggregation

biggraphite/drivers/cassandra.py
Speeds up check for metric existence by the carbon plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/74)
=> Performance: Skip metric index if no glob

CASSANDRA_DESIGN.md, CONFIGURATION.md, CONTRIBUTING.md, biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, biggraphite/graphite_utils.py, biggraphite/plugins/carbon.py, biggraphite/test_utils.py, biggraphite/utils.py, share/schema.cql, tests/test_carbon.py, tests/test_graphite_utils.py, tests/test_import_whisper.py
- Create an in-memory driver from FakeAccessor.
- Change settings to be able to support multiple drivers.
- Update documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/78)
=> drivers: add in-memory driver

biggraphite/plugins/graphite.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/81)
=> graphite: call the right util module

biggraphite/drivers/_downsampling.py, tests/test_drivers_downsampling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/66)
=> Return current aggregates in Downsampler.feed

biggraphite/cli/bgutil.py, biggraphite/cli/command.py, biggraphite/cli/command_read.py, biggraphite/cli/command_shell.py, biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, requirements.txt, setup.py
Currently with 'bgutil shell' and 'bgutil read'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/83)
=> Add 'bgutil' command line utility

biggraphite/accessor.py, biggraphite/drivers/_downsampling.py, tests/test_drivers_downsampling.py
Downsampler.feed() should not return already emitted stage0 points
else we end up write 20 points each time. Also rename 'raw' to 'stage0'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/104)
=> downsampling: don't re-write stage0 points multiple times

biggraphite/plugins/graphite.py
Not caught by the tests because all this part it mocked.. for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/105)
=> plugins/graphite: fix accessor init

biggraphite/cli/import_whisper.py, requirements.txt, tests/test_import_whisper.py
These two options will allow us to reduce the amount of data we
need to import. Also update progressbar now that it's fixed upstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/112)
=> cli: add --no-data and --ignored_stages to bg-import-whisper

biggraphite/drivers/cassandra.py
This is more efficient and available on almost every
modern platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/110)
=> cassandra: always use the TokenAwareLoadBalancingPolicy

CONFIGURATION.md, CONTRIBUTING.md, USAGE.md, biggraphite/plugins/carbon.py, tests/test_carbon.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/114)
=> Add new double-write plugins

biggraphite/accessor.py, biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, biggraphite/metadata_cache.py, biggraphite/plugins/carbon.py, biggraphite/test_utils.py, tests/test_drivers_downsampling.py, tests/test_metadata_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/113)
=> Add UUID to metrics

biggraphite/plugins/carbon.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/115)
=> carbon: re-create the metrics if it misses from any backend

biggraphite/accessor.py, biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/120)
=> Shift offset by two bytes

biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/121)
=> Round row timestamp to 1000 seconds

biggraphite/cli/bg_carbon_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/122)
=> carbon: improve compatibility

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/125)
=> Bump to 0.3

CONTRIBUTING.md, biggraphite/graphite_utils.py, biggraphite/plugins/carbon.py, tests/test_graphite_utils.py
The conf refactor patch broke the plugins without breaking the
unit tests. Add more unit tests. We should also mock less when
testing the plugins (to be done later).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/126)
=> graphite: fix graphite plugins

biggraphite/drivers/cassandra.py
bg-import-whisper uses multiprocessing to parallelize the
import.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/127)
=> cassandra: make bulkimport compatible with multiprocessing

tools/bg-generate-cassandra-sstables/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/128)
=> Add SSTable loader command line to README

tools/bg-generate-cassandra-sstables/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/131)
=> Generate bg-generate-cassandra-sstables uber-JAR

biggraphite/accessor.py, biggraphite/drivers/_downsampling.py, tests/test_accessor.py, tests/test_drivers_downsampling.py
I have no idea what .merge() was supposed to be used
for when we wrote it, but it clearly doesn't do what
we expected. Change it so it can merge aggregated values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/132)
=> aggregators: make .merge() work like we want it to works

biggraphite/drivers/cassandra.py, tests/test_cassandra.py
Will add a proper test in a later commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/137)
=> cassandra: fix repair()

pylama.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/141)
=> pylama: ignore D213

.travis.yml, CONTRIBUTING.md, biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/140)
=> Cassandra - Missing options and bump to 3.9

biggraphite/plugins/graphite.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/138)
=> graphite: do not keep un-connected accessors

biggraphite/cli/command_read.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/144)
=> command_read: accept metric name with * globbing

biggraphite/metadata_cache.py, biggraphite/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/148)
=> Faster tests

biggraphite/drivers/cassandra.py, tests/test_cassandra.py
Solves #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/149)
=> Implement globstar support for Cassandra driver

biggraphite/accessor.py, biggraphite/cli/bgutil.py, biggraphite/cli/command_du.py, requirements.txt
test_command_du is coming
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/146)
=> new|command_du: display disk usage of metrics

biggraphite/cli/bgutil.py, biggraphite/cli/command_info.py, biggraphite/cli/command_read.py
This solves #91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/145)
=> Extract metric metadata display to separate info command.

CONTRIBUTING.md, biggraphite/graphite_utils.py, tests/test_graphite_utils.py
See #154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/156)
=> Fix globbing

biggraphite/cli/bgutil.py, biggraphite/cli/command_write.py
Initial implementation of #89
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/151)
=> Add a write command to bgutil

tests/test_command_du.py
A test  file I forgot to add before for command_du
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/157)
=> bgutil du: missing test

biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, biggraphite/glob_utils.py, biggraphite/graphite_utils.py, biggraphite/plugins/graphite.py, biggraphite/utils.py, tests/test_glob_utils.py, tests/test_graphite_utils.py
- Fixes memory driver behaviour
- Cleaned tests up
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/155)
=> Proper glob post-filtering

biggraphite/cli/command_read.py, biggraphite/drivers/cassandra.py, biggraphite/plugins/carbon.py, biggraphite/plugins/graphite.py, requirements.txt, tests/test_cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/159)
=> Small cleanups

biggraphite/cli/bgutil.py, biggraphite/cli/command_du.py, biggraphite/cli/command_list.py, biggraphite/cli/command_read.py, tests/test_bgutil.py
you can ignore accessor and command_du, requirements, it's part of previous merge request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/150)
=> bgutil list

biggraphite/metadata_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/163)
=> Add timestamp info to metrics in cache

biggraphite/metadata_cache.py, tests-requirements.txt, tests/test_metadata_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/164)
=> Add test for timestamp update whilst time travelling

biggraphite/cli/bgutil.py, biggraphite/cli/command_clean.py, biggraphite/metadata_cache.py, tests/test_metadata_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/165)
=> Add method to clean cache from expired metrics

biggraphite/cli/command_list.py, biggraphite/drivers/cassandra.py, biggraphite/metadata_cache.py, share/schema.cql
- Add a prefix index and make use of it
- Add features to command_list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/168)
=> Make auto-completion faster

biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/171)
=> cassandra: make consistency levels more of less configurable

biggraphite/drivers/cassandra.py
See #174
This is a quick fix before we have a fully working #173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/175)
=> cassandra: don't use LIKE queries

biggraphite/cli/bgutil.py, biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, biggraphite/test_utils.py, tests/test_command_du.py, tests/test_command_repair.py, tests/test_command_test.py, tests/test_glob_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/178)
=> Make pylama happy again.

biggraphite/drivers/cassandra.py
Use the correct keywords
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/176)
=> cassandra: use the correct keyword

biggraphite/drivers/cassandra.py
Fixes #180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/181)
=> Replace None with UNSET_VALUE for Cassandra query padding

biggraphite/accessor.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, biggraphite/plugins/carbon.py, tests/test_carbon.py, tests/test_cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/177)
=> plugins/carbon: implement setMetadata/getMetadata(#88)

CONTRIBUTING.md, pom.xml, tools/bg-generate-cassandra-sstables/pom.xml
- Add comments in CONTRIBUTING.md
- Fix a typo in the groupId of the reactor pom
- Add project and env info to the Maven poms
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/182)
=> tools: cosmetic changes (comments, typo, ...)

biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, tests/test_cassandra.py
- Fix whisper import
- Fix cassandra driver with graphite-web
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/187)
=> whisper / cassandra fixes

biggraphite/accessor.py, biggraphite/cli/command_clean.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, biggraphite/metadata_cache.py, tests/test_cassandra.py
Leave your comment after the bip
*bip*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/185)
=> Cleanup metadata First try 

biggraphite/cli/command_clean.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/189)
=> bgutil clean: add posibility to set a cutoff to cache-clean

CHANGELOG.md, biggraphite/cli/command_list.py, biggraphite/plugins/graphite.py, setup.py, tests/test_graphite.py
Since metrics could be in `metrics` and not in `metrics_metadata`
we need to make sure that we don't break.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/190)
=> graphite: handle non-existing metrics gracefully

biggraphite/drivers/cassandra.py, tests/test_cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/191)
=> cassandra: better error when globing many directories

biggraphite/drivers/cassandra.py, tests/test_cassandra.py
Fixes issues described in #192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/194)
=> Fix cassandra query optimizer

biggraphite/cli/bgutil.py, biggraphite/cli/command_daemon.py, biggraphite/cli/command_repair.py, tests/test_bgutil.py, tests/test_command_daemon.py
Work in-progress, leave feedback anyway
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/195)
=> Bgutil daemon

biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/196)
=> cassandra clean: fix timeuuid, work in progress

biggraphite/cli/command_daemon.py
* Display timestamp and log level
* Stop threads on interrupt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/197)
=> bgutil: daemon enhancements

biggraphite/accessor.py, biggraphite/cli/command_repair.py, biggraphite/drivers/cassandra.py, biggraphite/metadata_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/199)
=> Repair improvements

tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/200)
=> travis: set JAVA_HOME correctly

biggraphite/cli/command_daemon.py, biggraphite/cli/command_repair.py, biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/201)
=> repair: add progress bar

biggraphite/accessor.py, biggraphite/metadata_cache.py, biggraphite/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/205)
=> Fix comments

CONTRIBUTING.md, biggraphite/accessor.py, biggraphite/drivers/_delayed_writer.py, biggraphite/drivers/_downsampling.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, biggraphite/plugins/carbon.py, tests/test_cassandra.py, tests/test_drivers_downsampling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/208)
=> cassandra: write optimisations

biggraphite/drivers/_utils.py, biggraphite/drivers/cassandra.py, biggraphite/test_utils.py, biggraphite/utils.py, tests/test_graphite_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/212)
=> cache ttl settings + cassandra multi cluster

biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, biggraphite/metadata_cache.py, biggraphite/plugins/carbon.py, biggraphite/utils.py, tests/test_carbon.py, tests/test_graphite_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/213)
=> carbon: create metrics asynchronously

biggraphite/graphite_utils.py, biggraphite/metadata_cache.py, biggraphite/plugins/carbon.py, biggraphite/utils.py, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/215)
=> Fix BG_CACHE_SYNC and add instrumentation

CONTRIBUTING.md, biggraphite/__init__.py, biggraphite/accessor.py, biggraphite/cli/bgutil.py, biggraphite/cli/command_syncdb.py, biggraphite/drivers/_utils.py, biggraphite/drivers/cassandra.py, biggraphite/plugins/carbon.py, biggraphite/test_utils.py, biggraphite/threads.py, biggraphite/utils.py, tests/test_cassandra.py, tests/test_command_syncdb.py, tests/test_command_test.py, tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/216)
=> more metrics and batches

biggraphite/drivers/cassandra.py, biggraphite/plugins/carbon.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/218)
=> carbon / cassandra optimisations

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/219)
=> Update CONTRIBUTING comments

biggraphite/drivers/cassandra.py
Forgot to commit this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/220)
=> Expose internal metrics of cassandra through Prometheus

CHANGELOG.md, CONFIGURATION.md, CONTRIBUTING.md, USAGE.md, biggraphite/accessor.py, biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, tests/test_accessor.py, tests/test_cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/221)
=> cassandra: separate stage0 and aggregated metrics

biggraphite/cli/import_whisper.py, biggraphite/plugins/graphite.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/224)
=> pylama: fix lint errors

biggraphite/plugins/carbon.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/225)
=> carbon: more aggressive rate-limiting for creations

biggraphite/cli/import_whisper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/227)
=> import-whisper: add the ability to filter out points by timestamp

biggraphite/drivers/cassandra.py, tests/test_command_test.py
+ Consistent argument parsing and syntax with whatever argument number
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/228)
=> Fix command line parsing

.travis.yml, CONTRIBUTING.md, benches/__init__.py, benches/bench_test.py, biggraphite/drivers/cassandra.py, biggraphite/test_utils.py, tests-requirements.txt, tox.ini
+ In progress, will add more bench
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/223)
=> Bench: Integration of bench tool

biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/231)
=> Repair: Fix deadlock

CHANGELOG.md, biggraphite/accessor.py, biggraphite/metadata_cache.py, biggraphite/plugins/carbon.py, biggraphite/plugins/graphite.py, tests/test_carbon.py
See commits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/233)
=> Cache and Creation

CHANGELOG.md, biggraphite/cli/command_daemon.py, biggraphite/metadata_cache.py, biggraphite/plugins/carbon.py, biggraphite/test_utils.py, biggraphite/utils.py, setup.py
Unless we discover something really wrong, this will mark 0.7.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/234)
=> Prepare 0.7.0 release

biggraphite/cli/clusters_diff.py, biggraphite/drivers/cassandra.py, tests/test_cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/238)
=> Small fixes

biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, tests/test_import_whisper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/239)
=> cassandra and import fixes

biggraphite/cli/clusters_diff.py, biggraphite/cli/replay_traffic.py, setup.py, tests-requirements.txt, tests/test_replay_traffic.py
Reads pcap dump from tcpdump and replays traffic.
Useful for benchmarks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/244)
=> cli: Add replay_traffic cli

CHANGELOG.md, biggraphite/drivers/cassandra.py
resolves #107 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/243)
=> Add statistics on used metrics (#107)

biggraphite/plugins/graphite.py, tests/test_graphite.py
issue #97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/246)
=> plugins/graphite: support carbon protocol

CHANGELOG.md, CONFIGURATION.md, biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/248)
=> cassandra: make consistency configurable #242

biggraphite/drivers/cassandra.py
This fixes #193.
We could also had an argument to glob_directories() but I choose to
do a simple select.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/249)
=> cassandra: do a simpler query for has_directory()

biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/250)
=> cassandra: fix repair command when there is an exception

CHANGELOG.md, CONFIGURATION.md, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/252)
=> Release 0.8.0

biggraphite/plugins/carbon.py, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/253)
=> carbon: run background tasks every 'CARBON_METRIC_INTERVAL'

biggraphite/glob_utils.py, tests/test_glob_utils.py
- Implemented a new graphite glob pattern tokenizer
- Rewrote regex generation using it
- Fixes #240 and adds regression test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/254)
=> Rewrite graphite glob to regex conversion

biggraphite/cli/bg_carbon_aggregator_cache.py, biggraphite/utils.py, setup.py, tests/test_bg_carbon_aggregator_cache.py, tests/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/256)
=> Add support for carbon_aggregator_cache

biggraphite/accessor.py, biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/258)
=> cassandra: handle out-of-retention queries correctly

biggraphite/plugins/graphite.py, tests/test_graphite.py
- instantiate it only once
- move some functions into private members
- support callable carbonlink (it's becoming a singleton in new graphite versions)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/259)
=> graphite: better carbonlink support

CHANGELOG.md, biggraphite/drivers/cassandra.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/260)
=> Last changes before v0.8.1

biggraphite/drivers/cassandra.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/264)
=> cassandra: add more comments in the schema

biggraphite/cli/bgutil.py, biggraphite/cli/command_copy.py, biggraphite/cli/command_list.py, biggraphite/cli/command_read.py, biggraphite/test_utils.py, tests/test_command_copy.py, tests/test_graphite.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/266)
=> Add bgutil copy <src> <dst> (#263)

biggraphite/accessor.py, biggraphite/cli/command_copy.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, tests/test_accessor.py, tests/test_command_copy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/267)
=> bgutil copy : store aggregated points correctly (#263)

biggraphite/cli/command_copy.py, tests/test_command_copy.py
Points are copied only from a given stage to a stage with the same precision.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/criteo/biggraphite/270)
=> bgutil copy : manage retention override

biggraphite/__init__.py
This conflict with graphite logger
=> remove biggraphite log handler

biggraphite/accessor.py, biggraphite/cli/bgutil.py, biggraphite/cli/command.py, biggraphite/cli/command_clean.py, biggraphite/cli/command_repair.py, biggraphite/cli/command_stats.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, biggraphite/plugins/graphite.py, requirements.txt, tests/test_command_daemon.py, tests/test_command_stats.py, tests/test_graphite.py
See https://github.com/criteo/biggraphite/issues/265
=> bgutil stats and more configs for cassandra

biggraphite/drivers/cassandra.py
This will help us debuging slow globs
=> cassandra: add the glob in the query exception

pom.xml, tools/graphiteindex/README.md, tools/graphiteindex/pom.xml, tools/graphiteindex/src/main/java/com/criteo/biggraphite/graphiteindex/GraphiteSASI.java, tools/graphiteindex/src/main/java/com/criteo/biggraphite/graphiteindex/GraphiteSASIBuilder.java, tools/graphiteindex/src/main/java/com/criteo/biggraphite/graphiteindex/MetricPath.java, tools/graphiteindex/src/main/java/com/criteo/biggraphite/graphiteindex/MetricsIndex.java, tools/graphiteindex/src/main/java/com/criteo/biggraphite/graphiteindex/MetricsIndexCollector.java, tools/graphiteindex/src/main/java/com/criteo/biggraphite/graphiteindex/PerSSTableIndexWriter.java, tools/graphiteindex/src/test/java/com/criteo/biggraphite/graphiteindex/MetricsIndexQueriesTest.java
Beginning an implementation of a Graphite SSTable-Attached Index.
This is still a lot of work to be operational… please see README.md for details.
=> Initial PoC for GraphiteSASI

biggraphite/plugins/carbon.py
=> carbon: make sure we touch metrics on all code path

CONTRIBUTING.md, USAGE.md, biggraphite/plugins/carbon.py, biggraphite/plugins/graphite.py, biggraphite/plugins/tags.py, tests/test_carbon.py, tests/test_graphite.py, tests/test_tags.py
Adds a new empty tag db and make sure we are compatible with the upcomming
Graphite version which has some breaking changes.
=> tags: add boilerplate for tags

biggraphite/plugins/carbon.py
This way this doesn't block ingestion.
=> carbon: call background operations in a thread

biggraphite/drivers/cassandra.py
See https://datastax-oss.atlassian.net/browse/PYTHON-643
=> cassandra: shuffle replicas

CONFIGURATION.md, biggraphite/drivers/cassandra.py, biggraphite/graphite_utils.py, biggraphite/metadata_cache.py, biggraphite/plugins/carbon.py, biggraphite/plugins/graphite.py, biggraphite/utils.py
* Add metrics for a bunch of things, including operations that can often be slow.
* Make SYNC_EVERY_N_WRITES configurable to reduce write latency
* Fix cassandra connection leak when open fails
=> Add metrics

CONFIGURATION.md, biggraphite/accessor.py, biggraphite/cli/command_clean.py, biggraphite/cli/command_read.py, biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/memory.py, tests/test_accessor.py, tests/test_cassandra.py, tests/test_command_clean.py, tests/test_import_whisper.py
This removes metrics with missing metadata.
=> bgutil clean: add `--corrupted-metrics`

biggraphite/accessor.py
=> Add non-zero timeout to event.wait()

ELASTICSEARCH_DESIGN.md, biggraphite/drivers/elasticsearch.py, biggraphite/utils.py, requirements.txt, tools/elasticsearch/import-metrics.py
This version can only connect to elasticsearch and do
nothing else.
=> elasticsearch: first version

.gitignore
As described in CONTRIBUTING.md
=> Ignore downloaded Cassandra archive

scripts/README.md, scripts/cassandra_env.sh, scripts/env.sh, scripts/init_cassandra.sh, scripts/run_carbon.sh, scripts/run_cassandra.sh, scripts/run_graphite_web.sh
Includes:
* Cassandra
* Carbon
* Graphite Web
=> Add scripts to help running test services

biggraphite/drivers/elasticsearch.py
list `foo` should return `foo`
list `foo.` should return `foo`
=> ES: fix list on directory

biggraphite/accessor.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/elasticsearch.py, biggraphite/drivers/memory.py
It was duplicated in both accessors
=> Move make_metric to accessor class

scripts/env.sh, tests-requirements.txt
- tox added to test-requirements
- obsolete comment removed from env.sh
=> Small changes

CONTRIBUTING.md, tools/mount-tmpfs.sh
=> Mount tmpfs for Cassandra and Elasticsearch data

biggraphite/drivers/elasticsearch.py, tests/drivers/test_elasticsearch.py
* `created_on` should be consistent accross indices
* `updated_on` is updated only on current index
* conversions from metric to ES document should copy date attributes
=> ES: fix metadata dates

MANIFEST.in, biggraphite/drivers/elasticsearch.py, share/es_schema.json
Future work could override the default path if needed
=> Make es schema configurable

benchmarks/accessor_bench.py, biggraphite/accessor.py, biggraphite/cli/command_copy.py, biggraphite/cli/command_write.py, biggraphite/cli/import_whisper.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/elasticsearch.py, biggraphite/metadata_cache.py, biggraphite/metric.py, biggraphite/plugins/carbon.py, tests/cli/test_bgutil.py, tests/cli/test_command_delete.py, tests/cli/test_command_du.py, tests/cli/test_command_graphite_web.py, tests/cli/test_command_list.py, tests/cli/test_command_read.py, tests/cli/test_command_stats.py, tests/drivers/base_test_metadata.py, tests/drivers/test_cassandra.py, tests/drivers/test_drivers_delayed_writer.py, tests/drivers/test_drivers_downsampling.py, tests/drivers/test_elasticsearch.py, tests/drivers/test_hybrid.py, tests/plugins/test_carbon.py, tests/test_accessor.py, tests/test_metric.py, tests/test_utils.py
Also moved Metric in its own file
=> Move make_metric to a static method.

biggraphite/accessor_factory.py, biggraphite/cache_factory.py, biggraphite/cli/bgutil.py, biggraphite/cli/command_graphite_web.py, biggraphite/cli/command_web.py, biggraphite/cli/commands.py, biggraphite/cli/import_whisper.py, biggraphite/graphite_utils.py, biggraphite/plugins/carbon.py, biggraphite/settings.py, biggraphite/utils.py, tests/cli/test_command_clean.py, tests/cli/test_command_delete.py, tests/cli/test_command_du.py, tests/cli/test_command_graphite_web.py, tests/cli/test_command_list.py, tests/cli/test_command_read.py, tests/cli/test_command_repair.py, tests/cli/test_command_stats.py, tests/cli/test_command_syncdb.py, tests/cli/test_command_test.py, tests/cli/test_command_web.py, tests/cli/test_command_write.py, tests/test_accessor_factory.py, tests/test_settings.py, tests/test_utils.py
Three classes have been extracted:
- settings
- accessor_factory
- cache_factory
=> Utils does not depend anymore on biggraphite modules.

MANIFEST.in, biggraphite/drivers/elasticsearch.py, biggraphite/drivers/elasticsearch_schema.json
=> Make Elasticsearch schema configurable

biggraphite/drivers/elasticsearch.py
This makes sure that touch_metric() will try
to look only in once index when updating update_on.
=> elasticsearch: optimize touch_metric()

biggraphite/drivers/cassandra.py
This is the port of #468 on 0.13.x branch
Metric removal is not ported on purpose (minor version change)
=> Port Cassandra queries instrumenting on 0.13.x branch

CHANGELOG.md, setup.py
Signed-off-by: Adrien Gentil <a.gentil@criteo.com>
=> Release 0.14.3

CHANGELOG.md, CONFIGURATION.md, biggraphite/drivers/cassandra.py, biggraphite/drivers/elasticsearch.py, biggraphite/plugins/graphite.py, biggraphite/plugins/middleware.py, biggraphite/tracing.py, setup.py
Improve tracing by:
- Better choice in the function to trace (less noise from missleading functions)
- More data inserted along opencensus default attributes
- Provides a middleware for tracing (add more data and configuration options)
=> Improve tracing 

biggraphite/tracing.py
=> fix crash when not using opencensus

README.md
Signed-off-by: Jean-Francois Weber-Marx <jf.webermarx@criteo.com>
=> Fixed ELASTICSEARCH_DESIGN.md link in README.md

.dockerignore, .gitignore, docker/.dockerignore, docker/README.md, docker/bg-cassandra/Dockerfile, docker/bg-elasticsearch/Dockerfile, docker/bg-helper/Dockerfile, docker/bg-kibana/Dockerfile, docker/build.sh, docker/docker-compose.yml, docker/graphite-aggregator-cache/Dockerfile, docker/graphite-web/Dockerfile
=> Adding docker-compose setup to test biggraphite

biggraphite/plugins/graphite.py
=> Pass correct time argument to carbonlink merge function

CHANGELOG.md, setup.py
=> Bump version to 0.14.9

CHANGELOG.md, setup.py
Signed-off-by: Adrien Gentil <a.gentil@criteo.com>
=> Release 0.14.10

biggraphite/drivers/elasticsearch.py
- Align the way the metadata are updated in Elasticsearch with Cassandra (merged in #500)
=> Align the way to update metadata in Elasticsearch with Cassandra

CHANGELOG.md, setup.py
=> Bump to 0.14.12

requirements.txt, tests-requirements.txt
=> Freeze gourde version to 0.2.1

requirements.txt
=> Version binding of depencies to stay python 2.x compatible

CHANGELOG.md, setup.py
=> Bump to 0.14.13

requirements.txt, tests-requirements.txt
- Align elasticsearch-dsl with elasticsearch version
- Opencensus tracer behaviour changed in the last version
=> Freeze dependency versions

CONFIGURATION.md, biggraphite/plugins/carbon.py, biggraphite/settings.py
Add the ability to configure the rate at which we create the metadata in database.
=> Make metadata rate limit configurable

ELASTICSEARCH_DESIGN.md, biggraphite/drivers/elasticsearch.py, setup.py
The directory index was added to speed up the directory queries. 
The write is implemented in carbon-relay-ng
=> Added a way to read directories on ES from a different index

.travis.yml, freeze-requirements.txt, requirements.txt
While I'm at it, fixing some broken deps.
=> Updating cassandra-driver to latest version.

biggraphite/accessor.py, biggraphite/cli/command.py, biggraphite/cli/command_clean.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/elasticsearch.py, biggraphite/drivers/hybrid.py, biggraphite/drivers/memory.py, setup.py
Reordoring clean steps; adding flags to disable cleaning parts.
=> Cleaning enhancements

.travis.yml, biggraphite/cli/command_clean.py, biggraphite/drivers/cassandra.py, biggraphite/metadata_cache.py, biggraphite/plugins/carbon.py, freeze-requirements.txt
Multiple improvement & bugfixes around Graphite cleaning:
* better progressbar;
* drop cache on metric not found due to inconsistent database;
* don't fail too much on backend exception during cleaning;
* fixing travis build.
=> Cleaning improvement & bugfixes

CONTRIBUTING.md, biggraphite/accessor.py, biggraphite/cli/command_clean.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/elasticsearch.py, biggraphite/drivers/hybrid.py, biggraphite/drivers/memory.py
Improving cleaning by:
- Adding a way to bypass some offsets automatically if Cassandra not responsive;
- Adding more metrics, especially on cleaning;
- Catch Exceptions on directory cleaning.
=> Multiple cleaning enhancements & fixes.

biggraphite/accessor.py, biggraphite/cli/command_clean.py, biggraphite/drivers/cassandra.py, biggraphite/drivers/elasticsearch.py, biggraphite/drivers/hybrid.py, biggraphite/drivers/memory.py
Adding 2 new ways to clean outdated metrics, and adding several possible tweaks using env. variables.
=> Clean expired metrics: New algorithm, tweaks

CASSANDRA_SSL.md, CONFIGURATION.md, biggraphite/drivers/cassandra.py
Added & checked:
* server/host name check;
* auth by client certificate/key.
* some docs.
=> Improve TLS/SSL support for cassandra.

biggraphite/cli/command_repair.py, biggraphite/drivers/cassandra.py
In cassandra, there might be some rogue metrics records which does not
have anymore any metrics_metadata records. This new feature, usable
when doing a bgutil repair, will check for each metrics records if
the metrics_metadata counterpart still exists, and if not, delete it.
=> Adding a way to clean up dead metrics records in Cassandra.
